<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Promise</title>
</head>
<body>
  <script type="text/javascript">
    // 1、 new Promise((resolve, reject) => { }).then(res => {}).catch(err => {})
    // let a = 1;
    // let panDun = new Promise((resolve, reject) => {
    //   if(a === 10) {
    //     // 返回正确的  你想要的东西
    //     resolve(`条件成立${a}`)
    //   }else {
    //     // 返回不正确的  用于给用户提示
    //     reject(`条件不成立${a}`)
    //   }
    // })
    // panDun.then(res => {
    //   console.log("res:", res)
    // }).catch(err => {
    //   console.log("err:", err)
    // })

    // 2、 Promise.all(); 把Promise对象进行打包, 打包好了之后扔到一个数组中，打包之后还是一个Promise对象，必须所有的都成功才能成功返回 then()
    // let p1 = Promise.resolve('aaa')
    // let p2 = Promise.resolve('bbb')
    // let p3 = Promise.resolve('ccc')
    // Promise.all([p1, p2, p3]).then(res => {
    //   console.log("res:", res)
    // }).catch(err => {
    //   console.log("err:", err)
    // })

    // 3、 Promise.race() 只要第一个成功，就返回  then() 否则就 catch()
    // let p1 = Promise.resolve('aaa')
    // let p2 = Promise.reject('bbb')
    // let p3 = Promise.reject('ccc')
    // Promise.race([p1, p2, p3]).then(res => {
    //   console.log("res:", res)
    // }).catch(err => {
    //   console.log("err:", err)
    // })
    

    // let loginStatus = 1
    // let isLogin = false
    // let loginHandel = new Promise ((resolve, reject) => {
    //   setTimeout(() => {
    //     if(loginStatus === 1) {
    //       resolve({code: 0, msg: '成功', data: {isLogin: true}})
    //     }else {
    //       reject({code: 500, msg: '失败', data: {isLogin: false}})
    //     }
    //   }, 1000)
    // })

    // let getUserInfo = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     if(loginStatus === 1) {
    //       resolve({code: 0, msg: '成功', data: {name: 'liuminghao'}})
    //     }else {
    //       reject({code: 500, msg: '失败'})
    //     }
    //   }, 1000)
    // })

    // loginHandel.then(res => {
    //   console.log("登录成功res:", res)
    //   if(res.code === 0) {
    //     if(res.data.isLogin) {
    //       getUserInfo.then(res => {
    //         console.log("获取用户信息成功res:", res)
    //       }).catch(err => {
    //         console.log("获取用户信息失败err:", err)
    //       })
    //     }
    //     return
    //   }
    //   throw new Error(res.msg)
    // }).catch(err => {
    //   console.log("登录失败err:", err)
    // })
    


    let loginStatus = 1
    let isLogin = false
    let loginHandel = (resolve, reject) => {
      setTimeout(() => {
        if(loginStatus === 1) {
          resolve({code: 0, msg: '成功', data: {isLogin: true}})
        }else {
          reject({code: 500, msg: '失败', data: {isLogin: false}})
        }
      }, 1000)
    }

    let getUserInfo = (resolve, reject) => {
      setTimeout(() => {
        if(loginStatus === 1) {
          resolve({code: 0, msg: '成功', data: {name: 'liuminghao'}})
        }else {
          reject({code: 500, msg: '失败'})
        }
      }, 1000)
    }

    new Promise(loginHandel).then(res => {
      console.log("登录成功res:", res)
      new Promise(getUserInfo).then(res => {
        console.log("获取用户信息成功res:", res)
      }).catch(err => {
        console.log("获取用户信息失败err:", err)
      })
    }).catch(err => {
      console.log("登录失败err:", err)
    })
  </script>
</body>
</html>